name: Deploy to ECS EC2

on:
  push:
    branches:   
      - 'feature/terraform-for-ecs-ec2' 

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  fmt-validate:
    name: Terraform fmt validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt validate
        working-directory: deploy/terraform/ecs/default
        run: |
          terraform init -input=false -backend=false
          terraform fmt -check -recursive
          terraform validate 

  tflint:
    name: Terraform TFLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
            tflint_version: latest

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        working-directory: deploy/terraform/ecs/default
        run: tflint -f compact --recursive

  deploy:
    needs: 
      - tflint
      - fmt-validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: deploy/terraform/ecs/default
        run: terraform init

      - name: Terraform plan
        working-directory: deploy/terraform/ecs/default
        run: |
          terraform plan \
            -var="environment_name=dev" \
            -var="image_tag=0.1.1" \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}"

      - name: Terraform apply
        id: terraform_apply
        working-directory: deploy/terraform/ecs/default
        run: |
          terraform apply \
            -auto-approve \
            -var="environment_name=dev" \
            -var="image_tag=0.1.1" \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}"
 